import Head from "next/head";

const SinglePostPage = () => {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>Post view</div>
      </main>
    </>
  );
};

export default SinglePostPage;
